//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundOfQuality.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public Managers()
        {
            this.SoundSystems = new HashSet<SoundSystems>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<SoundSystems> SoundSystems { get; set; }
    }
}
