//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundOfQuality.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.SoundSystems = new HashSet<SoundSystems>();
        }
    
        public int ID { get; set; }
        public int IDCustomer { get; set; }
        public int IDProduct { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string TotalAmount { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
        public virtual ICollection<SoundSystems> SoundSystems { get; set; }
    }
}
