//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundOfQuality.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Orders = new HashSet<Orders>();
            this.SoundSystems = new HashSet<SoundSystems>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public decimal Price { get; set; }
        public string AmountInStock { get; set; }
        public string Description { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<SoundSystems> SoundSystems { get; set; }
    }
}
